Language: Default (ENG)
Style: Default
LastApplied:
  SrcExe: C:/Gravity/Ragnarok/2025-06-04_Ragexe_1748494356_patched.exe
  TgtExe: C:/Gravity/Ragnarok/2025-06-04_Ragexe_1748494356_patched_patched.exe
ProfileConv:
  LogFile: C:\Users\dtg\Documents\WARP\Patches\Premium.yml
  DbFile: C:\Users\dtg\Documents\WARP\Patches\Premium.yml
  Target: C:\Users\dtg\Documents\WARP\Patches\Premium.yml
LastTestDir: C:/Users/dtg/Documents/GitHub/ROclient_en